[package]
name = "lockfree-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
concurrent-queue = { version = "2.5.0", optional = true }
core_affinity = "0.8.1"
lockfree = { version = "0.5.1", optional = true }
crossbeam = { version = "0.8", optional = true }
jemallocator = { version = "0.5.4", optional = true }

[features]
default = []
lockfree_queue = ["dep:lockfree"]
basic_queue = []
concurrent_queue = ["dep:concurrent-queue"]
array_queue = ["dep:crossbeam"]
memory_tracking = ["dep:jemallocator"]
